force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{0000}</displayFormat>
        <label>Bank Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current Account</fullName>
            </value>
            <value>
                <fullName>Saving Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account_History__c/Bank_Account_History__c.object-meta.xml
<CustomObject>
    <label>Bank Account History</label>
    <nameField>
        <displayFormat>BAH-{0000}</displayFormat>
        <label>Bank Account History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Account Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account_History__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Bank Account Histories</relationshipLabel>
    <relationshipName>Bank_Account_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account_History__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Withdrawal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PbBanksLWCController.cls
/* Purpose: This class is used to handle all server logic for PB Banks
 * Created By: Nelson Samuel J
 * Created On: 10-06-2026
 */
public with sharing class PbBanksLWCController {
    
    // This method is used to validate Loginner and return the object
    @AuraEnabled
    public static Object checkValidCustomer(String strCustomerId, Integer strPinNumber){
        try {
            Contact objCon = [SELECT Id, LastName FROM Contact WHERE LastName = :strCustomerId AND Pin_Number__c = :strPinNumber LIMIT 1];
            return objCon;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    // This method is used to get Amount by Account type and Customer Id
    @AuraEnabled
    public static Object getBankAcc(Id idCustomer, String strCustomerType){
        try {
            Bank_Account__c objBankAcc = [SELECT Id,Amount__c ,Account_Type__c, Contact__c  
                                        FROM Bank_Account__c  
                                        WHERE Account_Type__c = :strCustomerType AND Contact__c = :idCustomer LIMIT 1];
            return objBankAcc;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    // This method is used to get History Data
    @AuraEnabled
    public static List<Object> getBankHistory(Id idCustomer, String strStartDate, String strEndDate){
        
        // Dynamic Query
        String strQuery =
            'SELECT Bank_Account__r.Account_Type__c, Amount__c, Created_Date__c, Transaction_Type__c ' +
            'FROM Bank_Account_History__c ' +
            'WHERE Bank_Account__r.Contact__c = \'' + idCustomer + '\'';
        
        // From start date onwards
        if (String.isNotBlank(strStartDate)) {
            Date datStart = Date.valueOf(strStartDate.trim());
            strQuery += ' AND Created_Date__c >= :datStart';
        }
        
        // Until end date
        if (String.isNotBlank(strEndDate)) {
            Date datEnd = Date.valueOf(strEndDate.trim());
            strQuery += ' AND Created_Date__c <= :datEnd';
        }
        
        // Order transactions by newest first
        strQuery += ' ORDER BY CreatedDate DESC';
        
        try {
            List<Bank_Account_History__c>  lstBankAccHistory = Database.query(strQuery);
            return lstBankAccHistory;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}